apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs
  namespace: do-myproject
  labels:
    type: my-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.geek.per.sg
    path: "/export/files"
