kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-pv-claim
  namespace: do-myproject
  labels:
    type: my-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
